using System;
using System.Collections.Generic;
using System.Text;

/*protected works like the private but works for the data accessibility to only
child class.It works from top to down and not top to up and also it works as public
for the child class. The inheritance is as same as the C/c++.*/


namespace C_Sharp_Project1_Console
{
    class Person
    {
        protected String name;
        protected void ShowName()
        {
            Console.WriteLine(" Name of Student :{0}", name);
        }
    }

    class Student : Person
    {
        public void setName(String n)
        {
            name = n;
        }

        public void display()
        {
            ShowName();
        }
    }

    class Program
    {
        public static void Main77()
        {
            Student s = new Student();
            s.setName("Aayush Sahay");
            s.display();

            Console.ReadKey();
        }
    }


}

/*Possiblility that other namespace resides the parent class and other namespace resides the child class
 By default class is internal , access within the same namespace/assembly.

 Internal is the default access specifier. internal then accessible within the same assembly or the
namespace.

protected internal will allow to expose the memebers to containing classes , child classes and the classes
within the same assembly. In addition it allows the access to the derived classes outside the assembly.

protected : class and subclass access
protected internal : same , sub class and other classes of the same assembly.
exe file is an assembly file that has the power to execute
DLL has a functionality , we use the dll to be utilised by the exe. The dll provides an exe
to implement any service . exe has a big bundle or required code , but dll helps any exe

class , interface , structs , enum and meta data is used .

MSIL is the Microsoft Intermediate language.
Well defined description of data is known as the MetaData.
msil : code of .net framework when compiled , it can be used by other platforms in the .NET Language.
it is ready to be used by J# , VBNET , it is as same as using the dll. it is the basic bulding block of the .net
it can be made the executable and used by the other application.

Types of assembly : Main() method is the entry point : the executable assembly.
DLL has to not run , it has to be used by other application. This is also a kind of assembly.

related to the com and DCOM
dll provides the reusable code and resources for the other application.

assembly contains msil , metadata, manifest and resources.
no need to give any command to it , it will make it automatically.

make in 1 language , give functionality to other codes.
it is a cpu independent language generated by the .net compilers

program -> compile ->msil+metadata + CLR(Common language Runtime.)
Java has a JIT : just in time compiler. it will convert the MSIL to the native machine code.
Then it will execute on the target machine . Part of JVM is JIT.
msil is platform independent , it will run on any system with clr.
it is the bytecode of the microsoft. it is generated from any .NET language

does the method calls , exception handling and object creation and security checks.

how to make the dll and to use it in the exe.

new project and select console.net frameork , name:our dll make the class library . 
Then create it. Ther will be a class made. There is no name , by default you get
the class1 

public class1{
public String greeting(){
    return "Hello Friends ";
}
}
Then compile the project.
go to the build. build our dll 1 , it will write that the dll completed .
Where it is stored. Right click the project. Open in file explorter

There in the bin>Debug>(find the OurDLL, used in the other project)

make a console app in the .net framework : named myWXE
Then how to use the dll , how ?
we will set the reference , inorder to aces:
references  : right click add references (in solution explorer)
find it and can do the import.

using MyDLL;

internal class program1{
    static void Main(){
        Class1 o = new Class1();
        String s = o.greeting();
        Console.WriteLine(s);

        Console.ReadKey();
    }
}
Then you run the project 
 */
